[package]
name = "crypto-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
openmls = "0.4"
openmls_traits = "0.1"
openmls_rust_crypto = "0.1"

base64 = "0.13.0"
uuid = "1.0.0-alpha"
clap = { version = "3", features = ["derive"] }

[dev-dependencies]
tempdir = "0.3"

[workspace]
