[package]
name = "mls-test-cli"
version = "0.6.0"
edition = "2021"

[dependencies]
openmls = { git = "https://github.com/openmls/openmls" }
openmls_traits = { git = "https://github.com/openmls/openmls" }
openmls_rust_crypto = { git = "https://github.com/openmls/openmls" }
openmls_basic_credential = { git = "https://github.com/openmls/openmls/" }
tls_codec = { version = "0.2.0", features = ["derive", "serde", "mls"] }
futures-lite = "1.12"
async-trait = "0.1"

base64 = "0.13.0"
uuid = "1.0.0-alpha"
clap = { version = "3", features = ["derive"] }

[patch.crates-io.hpke-rs]
git = "https://github.com/franziskuskiefer/hpke-rs.git"

[patch.crates-io.hpke-rs-crypto]
git = "https://github.com/franziskuskiefer/hpke-rs.git"

[patch.crates-io.hpke-rs-rust-crypto]
git = "https://github.com/franziskuskiefer/hpke-rs.git"

[patch.crates-io.tls_codec]
git = "https://github.com/wireapp/formats"
branch = "fix-partial-read"
package = "tls_codec"

[dev-dependencies]
tempdir = "0.3"

[workspace]
